/*
 * Common phrases. Used by the welcome page.
 * This page was automatically generated by the Flitter framework.
 */
module.exports = exports = {
    welcome: 'Bienvenido',
    powered_by_flitter: 'impulsado por flitter',
    new_to_flitter: '¿Nuevo en Flitter?',
    start_here: 'Empieza aqui.',
    log_out: 'Cerrar sesión',
}
