/*
 * Common phrases. Used by the welcome page.
 * This page was automatically generated by the Flitter framework.
 */
module.exports = exports = {
    welcome: 'Welcome',
    powered_by_flitter: 'powered by flitter',
    new_to_flitter: 'New to Flitter?',
    start_here: 'Start Here.',
    log_out: 'Log out',
}
